// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCBPqPTsjNDd5nERbXWYQtk2wC0XGWEng',
    appId: '1:254219176898:android:faf7e843b9da830b28645b',
    messagingSenderId: '254219176898',
    projectId: 'plugin-task',
    storageBucket: 'plugin-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl4wfnHvIGWti0Ai_vi0gxJusvucZwpEg',
    appId: '1:254219176898:ios:9eb352bf1a381e9f28645b',
    messagingSenderId: '254219176898',
    projectId: 'plugin-task',
    storageBucket: 'plugin-task.firebasestorage.app',
    iosBundleId: 'com.example.flutterPluginTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDseihRni893zYJEeRI4-5Y3pvCXYofH9o',
    appId: '1:254219176898:web:558d01e44fc0e1af28645b',
    messagingSenderId: '254219176898',
    projectId: 'plugin-task',
    authDomain: 'plugin-task.firebaseapp.com',
    storageBucket: 'plugin-task.firebasestorage.app',
    measurementId: 'G-06TXC08STF',
  );
}
